complete highest_sum and lowest_sum
ChrisAsercion/futbol pull request #18
Opened 2023-06-09 20:39 UTC by Captainlearyo

2023-06-09 21:11 UTC, JorjaF commented on lib/stat_tracker.rb
> +   p hash.values.max
even though the test passes i am unsure why this put is here

2023-06-09 21:12 UTC, JorjaF commented on lib/stat_tracker.rb
> +   p hash.values.min
even though the test passes i am unsure why this put is here

2023-06-09 21:13 UTC, JorjaF commented
there are a couple of puts that I am unsure of

2023-06-09 21:14 UTC, JorjaF requested changes
I am unsure why there are puts on here

2023-06-10 17:19 UTC, bserge13 approved these changes
Can't find anything I'd change. Good stuff!

2023-06-10 21:00 UTC, JorjaF approved these changes
looks good

2023-06-10 21:18 UTC, closed without merging