Clay sums attempt4
ChrisAsercion/futbol pull request #22
Opened 2023-06-10 23:26 UTC by Captainlearyo

2023-06-11 21:23 UTC, JorjaF approved these changes
I am glad we finally got this one on here,

2023-06-11 21:56 UTC, andilovetto commented on lib/stat_tracker.rb
> +    @game_factory.games.each do |i|
i think this looks great, clay! i think we should consider renaming the block variable to be more explicit as to what it represents and maybe also renaming the hash variable to be more explicit as well. 

maybe you could change the `i` to be `game` instead?

2023-06-11 21:57 UTC, andilovetto requested changes
i think for coder empathy and for the sake of readability, we should consider renaming the block variable `i` and the `hash` variable to something more explicit as to what those individual variables represent.

2023-06-12 03:01 UTC, Captainlearyo commented
i was changed to game

2023-06-12 14:56 UTC, ChrisAsercion commented
I checked and the block variables are changed to game. Thanks Clay!

2023-06-12 14:57 UTC, ChrisAsercion approved these changes
block variables changed to game on request has been made.

2023-06-12 15:10 UTC, andilovetto approved these changes
thanks for making the requested change. i still think we could change the hash variable to be more explicit as to what that hash is holding, but since you stated it was a placeholder, i think it's okay for now.

2023-06-12 15:12 UTC, merged